// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResourcesManager.Datas;

#nullable disable

namespace ResourcesManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317223627_AddV1ModelSaved")]
    partial class AddV1ModelSaved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResourcesManager.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ResourcesManager.Models.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedResources")
                        .HasColumnType("integer");

                    b.Property<int>("AddedTexts")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedTexts")
                        .HasColumnType("integer");

                    b.Property<int>("WarningsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportedByUserId");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("ResourcesManager.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("ResourcesManager.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedImportBatchId")
                        .HasColumnType("integer");

                    b.Property<string>("FamilyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SeenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedImportBatchId");

                    b.HasIndex("FamilyCode");

                    b.HasIndex("KeyName")
                        .IsUnique();

                    b.HasIndex("ResourceName");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("ResourcesManager.Models.ResourceText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedImportBatchId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReplacesTextId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("SeenCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TextValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedImportBatchId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ReplacesTextId");

                    b.HasIndex("ResourceId", "LanguageId");

                    b.ToTable("resource_texts", (string)null);
                });

            modelBuilder.Entity("ResourcesManager.Models.ImportBatch", b =>
                {
                    b.HasOne("ResourcesManager.Models.AppUser", "ImportedByUser")
                        .WithMany("ImportedBatches")
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportedByUser");
                });

            modelBuilder.Entity("ResourcesManager.Models.Resource", b =>
                {
                    b.HasOne("ResourcesManager.Models.AppUser", "CreatedByUser")
                        .WithMany("CreatedResources")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourcesManager.Models.ImportBatch", "CreatedImportBatch")
                        .WithMany("CreatedResources")
                        .HasForeignKey("CreatedImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("CreatedImportBatch");
                });

            modelBuilder.Entity("ResourcesManager.Models.ResourceText", b =>
                {
                    b.HasOne("ResourcesManager.Models.AppUser", "CreatedByUser")
                        .WithMany("CreatedResourceTexts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourcesManager.Models.ImportBatch", "CreatedImportBatch")
                        .WithMany("CreatedResourceTexts")
                        .HasForeignKey("CreatedImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ResourcesManager.Models.Language", "Language")
                        .WithMany("ResourceTexts")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourcesManager.Models.ResourceText", "ReplacesText")
                        .WithMany("ReplacedByTexts")
                        .HasForeignKey("ReplacesTextId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResourcesManager.Models.Resource", "Resource")
                        .WithMany("Texts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("CreatedImportBatch");

                    b.Navigation("Language");

                    b.Navigation("ReplacesText");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ResourcesManager.Models.AppUser", b =>
                {
                    b.Navigation("CreatedResourceTexts");

                    b.Navigation("CreatedResources");

                    b.Navigation("ImportedBatches");
                });

            modelBuilder.Entity("ResourcesManager.Models.ImportBatch", b =>
                {
                    b.Navigation("CreatedResourceTexts");

                    b.Navigation("CreatedResources");
                });

            modelBuilder.Entity("ResourcesManager.Models.Language", b =>
                {
                    b.Navigation("ResourceTexts");
                });

            modelBuilder.Entity("ResourcesManager.Models.Resource", b =>
                {
                    b.Navigation("Texts");
                });

            modelBuilder.Entity("ResourcesManager.Models.ResourceText", b =>
                {
                    b.Navigation("ReplacedByTexts");
                });
#pragma warning restore 612, 618
        }
    }
}
